apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx=ecdregistry123.azurecr.io/nginx-app
    argocd-image-updater.argoproj.io/nginx.update-strategy: latest
    argocd-image-updater.argoproj.io/nginx.allow-tags: regexp:^dev-.*
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: ecdregistry123.azurecr.io/nginx-app:dev-initial
          ports:
            - containerPort: 80