name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ecdregistry123.azurecr.io
  IMAGE_NAME: nginx-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login $REGISTRY -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Generate Tag
        run: echo "TAG=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t $REGISTRY/$IMAGE_NAME:$TAG ./app

      - name: Push image
        run: docker push $REGISTRY/$IMAGE_NAME:$TAG

      - name: Tag latest
        run: docker tag $REGISTRY/$IMAGE_NAME:$TAG $REGISTRY/$IMAGE_NAME:latest

      - name: Push latest
        run: docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Show tag
        run: echo "Built image with tag $TAG"